### ISSUE TITLE
Clicking Home does not bring you to Home when on Blog Post

### ISSUE THREAD

**Issue by kyleli** [AO-Design-Inc/featherWebsite-2.0#1]
### Expected Behavior
Clicking on the Home Button when on a blog post does not return you to home.

### Current Behavior
Sporadic consistency, sometimes pressing home returns you after a few seconds, other times it will never load.

### Steps to Reproduce
1. Go to feather.systems
2. Click Blog
3. Click on a Blog Post
4. Click on the Feather Logo

### Detailed Description
The site seems to infinitely load and the URL changes, however nothing appears on the screen. There is a similar delay when going from the Homepage to Blog.

**Comment by okirpane** [comment]
Solved
