### ISSUE TITLE
Site Description not working 

### ISSUE THREAD

**Issue by joGao01** [AO-Design-Inc/featherWebsite-2.0#10]
There is a meta description tag but Google chooses to display this instead:
![image](https://user-images.githubusercontent.com/36776982/150012022-608c0a35-1e98-4266-8323-3471b8c5275f.png)
Meta tag in app.html:
![image](https://user-images.githubusercontent.com/36776982/150012057-dd6fb5c4-c2b3-428e-858c-cacc73d6c12b.png)

To replicate:
- type "feather systems" into search and hit enter

**Comment by okirpane** [comment]
We will check again in a few days.

**Comment by okirpane** [comment]
<img width="605" alt="Screen Shot 2022-01-21 at 11 57 45 PM" src="https://user-images.githubusercontent.com/31450994/150580868-471f4ad4-aa76-4e50-9bbb-24a19085fb51.png">
Fixed
