### ISSUE TITLE
Highlighting "Read More" on Blog Banner Displays Weird Corners

### ISSUE THREAD

**Issue by kyleli** [AO-Design-Inc/featherWebsite-2.0#13]
### Expected Behavior
Highlighting Read More should only highlight read more and not affect the corners of the entire banner

### Current Behavior
When you highlight "Read More" on the banner, the corners have a white glow.

### Steps to Reproduce
Open feather.systems
Click Blog
Highlight "Read More"
Inspect edges of the frame

### Detailed Description
![d5d65c7a36d2ed1a7b98fb4d7cf54400](https://user-images.githubusercontent.com/1357336/150568095-864181e4-58e1-4c98-81f6-ccfb235e219c.gif)

**Comment by okirpane** [comment]
fixed
