### ISSUE TITLE
strikethrough happens twice

### ISSUE THREAD

**Issue by pretentious7** [AO-Design-Inc/featherWebsite-2.0#7]
notice that the pink strikethrough happens once then resets and happens again.

https://user-images.githubusercontent.com/29604460/149998107-ab619efb-c3d4-4e76-ab68-1ff972862f93.mp4

**Comment by pretentious7** [comment]
the issue is more pronounced when I'm not screenrecording, wonder why

**Comment by okirpane** [comment]
resolved by adding the animation class onMount
